deployment:
  tasks:
    - export DEPLOYPATH=/home/minsuedu/public_html
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/files $DEPLOYPATH
    - /bin/cp -R public/fonts $DEPLOYPATH
    - /bin/cp -R public/img $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - /bin/cp -R public/plugins $DEPLOYPATH
    - /bin/cp -R public/template $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/favicon.ico $DEPLOYPATH
    - /bin/cp public/mix-manifest.json $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH
    - /bin/cp public/web.config $DEPLOYPATH
